### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by Animesh-Ghosh**

### CODE REVIEW

**Comment by TwistingTwists** [comment]
```

  1) test greets the world (ElixirDelhiBotTest)
     test/elixir_delhi_bot_test.exs:5
     ** (UndefinedFunctionError) function ElixirDelhiBot.hello/0 is undefined or private
     code: assert ElixirDelhiBot.hello() == :world
     stacktrace:
       (elixir_delhi_bot 0.1.0) ElixirDelhiBot.hello()
       test/elixir_delhi_bot_test.exs:6: (test)

....    warning: ElixirDelhiBot.hello/0 is undefined or private
    │
  6 │     assert ElixirDelhiBot.hello() == :world
    │                           ~
    │
    └─ test/elixir_delhi_bot_test.exs:6:27: ElixirDelhiBotTest."test greets the world"/1


Finished in 0.05 seconds (0.05s async, 0.00s sync)
5 tests, 1 failure


```

**Comment by TwistingTwists** [comment]
every other test passes. :)

**Comment by TwistingTwists** [comment]
LGTM

**Comment by Animesh-Ghosh** [comment]
> ```
> 
>   1) test greets the world (ElixirDelhiBotTest)
>      test/elixir_delhi_bot_test.exs:5
>      ** (UndefinedFunctionError) function ElixirDelhiBot.hello/0 is undefined or private
>      code: assert ElixirDelhiBot.hello() == :world
>      stacktrace:
>        (elixir_delhi_bot 0.1.0) ElixirDelhiBot.hello()
>        test/elixir_delhi_bot_test.exs:6: (test)
> 
> ....    warning: ElixirDelhiBot.hello/0 is undefined or private
>     │
>   6 │     assert ElixirDelhiBot.hello() == :world
>     │                           ~
>     │
>     └─ test/elixir_delhi_bot_test.exs:6:27: ElixirDelhiBotTest."test greets the world"/1
> 
> 
> Finished in 0.05 seconds (0.05s async, 0.00s sync)
> 5 tests, 1 failure
> 
> 
> ```

I've yet to update the tests for all the relevant modules. I'll mark this Pull Request as ready once I am done.

**Pull request merged**
